version: '3'
services:
  postgresql:
    image: postgres
    container_name: nuber-eats-postgresql
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'dean'
      POSTGRES_PASSWORD: 'cksgh1217'
      TZ: 'Asia/Seoul'
